add platform support to the inspec example
simp/inspec-profile-disa_stig-el7 pull request #137
Opened 2020-01-17 17:25 UTC by aaronlippold

This will allow us to use a wrapper profile correctly between platforms

2020-01-21 17:10 UTC, trevor-vaughan approved these changes

2020-01-21 17:11 UTC, trevor-vaughan requested changes

2020-01-21 17:11 UTC, trevor-vaughan commented on inspec.yml
> +  - platform-name: redhat
This needs to be the entire supported list of CentOS, RHEL, OEL, etc... I think

2020-01-22 02:08 UTC, aaronlippold commented
I think we can use Linux as the key word then and I believe we can specify
that it's at least a release seven I'll have to look at the doc

On Tue, Jan 21, 2020, 12:11 PM Trevor Vaughan <notifications@github.com>
wrote:

> *@trevor-vaughan* requested changes on this pull request.
> ------------------------------
>
> In inspec.yml
> <https://github.com/simp/inspec-profile-disa_stig-el7/pull/137#discussion_r369131510>
> :
>
> > @@ -7,6 +7,10 @@ license: Apache-2.0
>  summary: 'The `disa_stig-el7` inspec profile helps scan your system aginst the DISA RHEL7 STIG'
>  version: 0.2.0
>
> +supports:
> +  - platform-name: redhat
>
> This needs to be the entire supported list of CentOS, RHEL, OEL, etc... I
> think
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/simp/inspec-profile-disa_stig-el7/pull/137?email_source=notifications&email_token=AALK42B2BRTIZA3UQ6B56LLQ64UFPA5CNFSM4KILTTMKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCSQEH5Q#pullrequestreview-346047478>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AALK42CLMLP6KPB5QKOYMLDQ64UFPANCNFSM4KILTTMA>
> .
>

2026-07-28 19:32 UTC, silug commented
Closing: this repository is **archived** and the profile targets **RHEL/CentOS 7**, which is end-of-life and has been removed from the SIMP supported-platform matrix entirely. The EL7 DISA STIG InSpec profile is no longer maintained here, so there is nowhere for this work to land.

This added platform support to the InSpec example so a wrapper profile could be used across platforms (+4 lines).

This is a cleanup of the archived repo's open-PR backlog, not a judgement on the change — thanks for taking the time to send it. The branch is left intact. Current compliance work lives in `simp/rubygem-simp-compliance_engine` and the open-source Sicura mappings.

2026-07-28 19:32 UTC, closed without merging